<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Events;
use Carbon\Carbon;


class event_seeders extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
<<<<<<< HEAD
    {
        //Event Seeders
        $eventRecords = [
            [
              'event_id' => 1,
              'user_id' => 4,
              'transaction_id' => 0,
              'wishlist_id' => 0,
              'talent_id' => 0,
              'event_price'=>20000,
              'event_name' => "Webinar LPPM",
              'event_location' => "LPPM UPN Veteran Jawa Timur",
              'event_date' => Carbon::now(),
              'event_city' => "Surabaya",
              'event_poster' => "surabaya.png",
              'event_description' => "Webinar bagus banget ini",
              'event_tag' => "Webinar",
                'event_status' => 'deactive',
              'created_at'=>Carbon::now(),
              'updated_at'=>Carbon::now()
            ],
            [
                'event_id' => 2,
                'user_id' => 4,
                'transaction_id' => 0,
                'wishlist_id' => 0,
                'talent_id' => 0,
                'event_price'=>20000,
                'event_name' => "Webinar LPPM - 2",
                'event_location' => "LPPM UPN Veteran Jawa Timur",
                'event_date' => Carbon::now(),
                'event_city' => "Surabaya",
                'event_poster' => "surabaya.png",
                'event_description' => "Webinar bagus banget ini",
                'event_tag' => "Webinar",
                'event_status' => 'deactive',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'event_id' => 3,
                'user_id' => 4,
                'transaction_id' => 0,
                'wishlist_id' => 0,
                'talent_id' => 0,
                'event_price'=>20000,
                'event_name' => "Webinar LPPM - 3",
                'event_location' => "LPPM UPN Veteran Jawa Timur",
                'event_date' => Carbon::now(),
                'event_city' => "Surabaya",
                'event_poster' => "surabaya.png",
                'event_description' => "Webinar bagus banget ini",
                'event_tag' => "Webinar",
                'event_status' => 'deactive',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'event_id' => 4,
                'user_id' => 4,
                'transaction_id' => 0,
                'wishlist_id' => 0,
                'talent_id' => 0,
                'event_price'=>20000,
                'event_name' => "Webinar LPPM - 4",
                'event_location' => "LPPM UPN Veteran Jawa Timur",
                'event_date' => Carbon::now(),
                'event_city' => "Surabaya",
                'event_poster' => "surabaya.png",
                'event_description' => "Webinar bagus banget ini",
                'event_tag' => "Webinar",
                'event_status' => 'deactive',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'event_id' => 5,
                'user_id' => 4,
                'transaction_id' => 0,
                'wishlist_id' => 0,
                'talent_id' => 0,
                'event_price'=>20000,
                'event_name' => "Webinar LPPM -5",
                'event_location' => "LPPM UPN Veteran Jawa Timur",
                'event_date' => Carbon::now(),
                'event_city' => "Surabaya",
                'event_poster' => "surabaya.png",
                'event_description' => "Webinar bagus banget ini",
                'event_tag' => "Webinar",
                'event_status' => 'deactive',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'event_id' => 6,
                'user_id' => 4,
                'transaction_id' => 0,
                'wishlist_id' => 0,
                'talent_id' => 0,
                'event_price'=>20000,
                'event_name' => "Webinar LPPM - 6",
                'event_location' => "LPPM UPN Veteran Jawa Timur",
                'event_date' => Carbon::now(),
                'event_city' => "Surabaya",
                'event_poster' => "surabaya.png",
                'event_description' => "Webinar bagus banget ini",
                'event_tag' => "Webinar",
                'event_status' => 'deactive',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'event_id' => 7,
                'user_id' => 4,
                'transaction_id' => 0,
                'wishlist_id' => 0,
                'talent_id' => 0,
                'event_price'=>20000,
                'event_name' => "Webinar LPPM - 7",
                'event_location' => "LPPM UPN Veteran Jawa Timur",
                'event_date' => Carbon::now(),
                'event_city' => "Surabaya",
                'event_poster' => "surabaya.png",
                'event_description' => "Webinar bagus banget ini",
                'event_tag' => "Webinar",
                'event_status' => 'deactive',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'event_id' => 8,
                'user_id' => 4,
                'transaction_id' => 0,
                'wishlist_id' => 0,
                'talent_id' => 0,
                'event_price'=>20000,
                'event_name' => "Webinar LPPM - 8",
                'event_location' => "LPPM UPN Veteran Jawa Timur",
                'event_date' => Carbon::now(),
                'event_city' => "Surabaya",
                'event_poster' => "surabaya.png",
                'event_description' => "Webinar bagus banget ini",
                'event_tag' => "Webinar",
                'event_status' => 'deactive',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'event_id' => 9,
                'user_id' => 4,
                'transaction_id' => 0,
                'wishlist_id' => 0,
                'talent_id' => 0,
                'event_price'=>20000,
                'event_name' => "Webinar LPPM - 9",
                'event_location' => "LPPM UPN Veteran Jawa Timur",
                'event_date' => Carbon::now(),
                'event_city' => "Surabaya",
                'event_poster' => "surabaya.png",
                'event_description' => "Webinar bagus banget ini",
                'event_tag' => "Webinar",
                'event_status' => 'deactive',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'event_id' => 10,
                'user_id' => 4,
                'transaction_id' => 0,
                'wishlist_id' => 0,
                'talent_id' => 0,
                'event_price'=>20000,
                'event_name' => "Webinar LPPM - 10",
                'event_location' => "LPPM UPN Veteran Jawa Timur",
                'event_date' => Carbon::now(),
                'event_city' => "Surabaya",
                'event_poster' => "surabaya.png",
                'event_description' => "Webinar bagus banget ini",
                'event_tag' => "Webinar",
                'event_status' => 'deactive',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'event_id' => 11,
                'user_id' => 4,
                'transaction_id' => 0,
                'wishlist_id' => 0,
                'talent_id' => 0,
                'event_price'=>20000,
                'event_name' => "Webinar LPPM - 10",
                'event_location' => "LPPM UPN Veteran Jawa Timur",
                'event_date' => Carbon::now(),
                'event_city' => "Surabaya",
                'event_poster' => "surabaya.png",
                'event_description' => "Webinar bagus banget ini",
                'event_tag' => "Webinar",
                'event_status' => 'deactive',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'event_id' => 12,
                'user_id' => 4,
                'transaction_id' => 0,
                'wishlist_id' => 0,
                'talent_id' => 0,
                'event_price'=>20000,
                'event_name' => "Webinar LPPM - 10",
                'event_location' => "LPPM UPN Veteran Jawa Timur",
                'event_date' => Carbon::now(),
                'event_city' => "Surabaya",
                'event_poster' => "surabaya.png",
                'event_description' => "Webinar bagus banget ini",
                'event_tag' => "Webinar",
                'event_status' => 'deactive',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'event_id' => 13,
                'user_id' => 4,
                'transaction_id' => 0,
                'wishlist_id' => 0,
                'talent_id' => 0,
                'event_price'=>20000,
                'event_name' => "Webinar LPPM - 10",
                'event_location' => "LPPM UPN Veteran Jawa Timur",
                'event_date' => Carbon::now(),
                'event_city' => "Surabaya",
                'event_poster' => "surabaya.png",
                'event_description' => "Webinar bagus banget ini",
                'event_tag' => "Webinar",
                'event_status' => 'deactive',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'event_id' => 14,
                'user_id' => 4,
                'transaction_id' => 0,
                'wishlist_id' => 0,
                'talent_id' => 0,
                'event_price'=>20000,
                'event_name' => "Webinar LPPM - 10",
                'event_location' => "LPPM UPN Veteran Jawa Timur",
                'event_date' => Carbon::now(),
                'event_city' => "Surabaya",
                'event_poster' => "surabaya.png",
                'event_description' => "Webinar bagus banget ini",
                'event_tag' => "Webinar",
                'event_status' => 'deactive',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'event_id' => 15,
                'user_id' => 4,
                'transaction_id' => 0,
                'wishlist_id' => 0,
                'talent_id' => 0,
                'event_price'=>20000,
                'event_name' => "Webinar LPPM - 10",
                'event_location' => "LPPM UPN Veteran Jawa Timur",
                'event_date' => Carbon::now(),
                'event_city' => "Surabaya",
                'event_poster' => "surabaya.png",
                'event_description' => "Webinar bagus banget ini",
                'event_tag' => "Webinar",
                'event_status' => 'deactive',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'event_id' => 16,
                'user_id' => 4,
                'transaction_id' => 0,
                'wishlist_id' => 0,
                'talent_id' => 0,
                'event_price'=>20000,
                'event_name' => "Webinar LPPM - 10",
                'event_location' => "LPPM UPN Veteran Jawa Timur",
                'event_date' => Carbon::now(),
                'event_city' => "Surabaya",
                'event_poster' => "surabaya.png",
                'event_description' => "Webinar bagus banget ini",
                'event_tag' => "Webinar",
                'event_status' => 'deactive',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'event_id' => 17,
                'user_id' => 4,
                'transaction_id' => 0,
                'wishlist_id' => 0,
                'talent_id' => 0,
                'event_price'=>20000,
                'event_name' => "Webinar LPPM - 10",
                'event_location' => "LPPM UPN Veteran Jawa Timur",
                'event_date' => Carbon::now(),
                'event_city' => "Surabaya",
                'event_poster' => "surabaya.png",
                'event_description' => "Webinar bagus banget ini",
                'event_tag' => "Webinar",
                'event_status' => 'deactive',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'event_id' => 18,
                'user_id' => 4,
                'transaction_id' => 0,
                'wishlist_id' => 0,
                'talent_id' => 0,
                'event_price'=>20000,
                'event_name' => "Webinar LPPM - 10",
                'event_location' => "LPPM UPN Veteran Jawa Timur",
                'event_date' => Carbon::now(),
                'event_city' => "Surabaya",
                'event_poster' => "surabaya.png",
                'event_description' => "Webinar bagus banget ini",
                'event_tag' => "Webinar",
                'event_status' => 'deactive',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'event_id' => 19,
                'user_id' => 4,
                'transaction_id' => 0,
                'wishlist_id' => 0,
                'talent_id' => 0,
                'event_price'=>20000,
                'event_name' => "Webinar LPPM - 10",
                'event_location' => "LPPM UPN Veteran Jawa Timur",
                'event_date' => Carbon::now(),
                'event_city' => "Surabaya",
                'event_poster' => "surabaya.png",
                'event_description' => "Webinar bagus banget ini",
                'event_tag' => "Webinar",
                'event_status' => 'deactive',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            [
                'event_id' => 20,
                'user_id' => 4,
                'transaction_id' => 0,
                'wishlist_id' => 0,
                'talent_id' => 0,
                'event_price'=>20000,
                'event_name' => "Webinar LPPM - 10",
                'event_location' => "LPPM UPN Veteran Jawa Timur",
                'event_date' => Carbon::now(),
                'event_city' => "Surabaya",
                'event_poster' => "surabaya.png",
                'event_description' => "Webinar bagus banget ini",
                'event_tag' => "Webinar",
                'event_status' => 'deactive',
                'created_at'=>Carbon::now(),
                'updated_at'=>Carbon::now()
            ],
            ];
            Events::insert($eventRecords);
    }
}
=======
   {
    //Event seeders
    $events = [];
    for ($i=1; $i <= 20 ; $i++) { 
        $new_arr = [
        'event_id' => $i,
        'user_id' => rand(4,6),
        'wishlist_id' => 0,
        'talent_id' => 0,
        'event_price'=>20000,
        'event_name' => "Webinar LPPM $i",
        'event_location' => "LPPM UPN Veteran Jawa Timur",
        'event_date' => Carbon::now(),
        'event_city' => "Surabaya",
        'event_poster' => "surabaya.png",
        'event_description' => "Webinar bagus banget ini",
        'event_tag' => "Webinar",
        'created_at'=>Carbon::now(),
        'updated_at'=>Carbon::now()
        ];
        array_push($events, $new_arr);
    };

    Events::insert($events);
   }
}
>>>>>>> 87eef8923718d79d92fcfc527c4f58d0ba532527
